let prophecies = [
    { "audio": "01", "text": "Fine", "interpretation": 0 },
    { "audio": "02", "text": "Good", "interpretation": 0 },
    { "audio": "03", "text": "Eh, okay", "interpretation": 0 },
    { "audio": "04", "text": "Acceptable", "interpretation": 0 },
    { "audio": "05", "text": "Complicated", "interpretation": 0 },
    { "audio": "06", "text": "More", "interpretation": 2 },
    { "audio": "07", "text": "Yes", "interpretation": 0 },
    { "audio": "08", "text": "No", "interpretation": 0 },
    { "audio": "09", "text": "Yes", "interpretation": 0 },
    { "audio": "10", "text": "Bad", "interpretation": 0 },
    { "audio": "11", "text": "Yes", "interpretation": 0 },
    { "audio": "12", "text": "Old", "interpretation": 1 },
    { "audio": "13", "text": "No", "interpretation": 0 },
    { "audio": "14", "text": "Hearing", "interpretation": 1 },
    { "audio": "15", "text": "More", "interpretation": 2 },
    { "audio": "16", "text": "Yes", "interpretation": 0 },
    { "audio": "17", "text": "Yes", "interpretation": 0 },
    { "audio": "18", "text": "Groceries", "interpretation": 1 },
    { "audio": "19", "text": "Bassy", "interpretation": 1 },
    { "audio": "20", "text": "Yes", "interpretation": 0 },
    { "audio": "21", "text": "No", "interpretation": 0 },
    { "audio": "22", "text": "Boring", "interpretation": 3 },
    { "audio": "23", "text": "Yes", "interpretation": 0 },
    { "audio": "24", "text": "Yes", "interpretation": 0 },
    { "audio": "25", "text": "Amazon", "interpretation": 1 },
    { "audio": "26", "text": "Yes", "interpretation": 0 },
    { "audio": "27", "text": "Yeah", "interpretation": 0 },
    { "audio": "28", "text": "Yes, yes, sometimes", "interpretation": 0 },
    { "audio": "29", "text": "Eh\u2026", "interpretation": 2 },
    { "audio": "30", "text": "Yes", "interpretation": 0 },
    { "audio": "31", "text": "No", "interpretation": 0 },
    { "audio": "32", "text": "Seven", "interpretation": 1 },
    { "audio": "33", "text": "Six", "interpretation": 1 },
    { "audio": "34", "text": "Seven", "interpretation": 1 },
    { "audio": "35", "text": "Upsetting", "interpretation": 4 },
    { "audio": "36", "text": "Yeah\u2026 no", "interpretation": 0 },
    { "audio": "37", "text": "No", "interpretation": 0 },
    { "audio": "38", "text": "Love", "interpretation": 5 },
    { "audio": "39", "text": "Jeremy", "interpretation": 1 },
    { "audio": "40", "text": "Ahh, yeah", "interpretation": 5 },
    { "audio": "41", "text": "Damn", "interpretation": 4 },
    { "audio": "42", "text": "Cheerio", "interpretation": 3 }
]

let interpretations = [
    "",
    "His words are mysterious\u2026",
    "You should provide more details.",
    "He seems tired.",
    "He seems perturbed.",
    "He seems pleased."
]

let jeremy = { "audio": "39", "twitter": "https://twitter.com/jeremyburge" }